version: '3.9'
services:
  backend:
    image: kpekala/habitgame-backend
    container_name: habitgame
    ports:
      - '30205:8080'
  frontend:
    image: kpekala/habitgame-frontend
    container_name: habitgame-ui
    ports:
      - '20205:4200'
    depends_on:
      - backend
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
